#!/usr/bin/bash
#TUtorial: https://youtu.be/qhCxKrU1AEY


#get first octets of network
ifconfig | grep "broadcast" | cut -d " " -f 10 | cut -d "." -f 1,2,3 | uniq > octets.txt

#set a variable to represent value of octet.txt
Octets=$(cat octets.txt)

#Create new .txt
echo "" > $Octets.txt

#Loop
for ip in {1..254}
do
	ping -c 1 $Octets.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> $Octets.txt &
done

#cat is used to read file in order and print standard output
cat $Octets.txt

#perform scan for local network
nmap -sS -iL $Octets.txt

## top-ports show the most common ports inr elation to our network

## bash script to path

#1 - $PATH
#use usr/local/bin from $PATH
# cd to the directory path
# cat pingbash to see if all lines can be read by linux


exit
